### 상품 추가
POST https://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN:

{
 "description": "상품 설명",
 "items": [
  {
    "count": 1,
    "name": "270",
    "price": 100000
  }
 ],
  "name": "나이키 에어포스"
}
### 이메일 인증 ( 고객 )
POST https://localhost:8082/signup/customer/verify?email=jungds95@naver.com&code=c8oNfeln0A
### 상품 아이템 추가
POST https://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN:

{
      "productId": 1,
      "count": 1,
      "name": "270",
      "price": 100000

}
### 이메일 인증 ( 고객 )
POST https://localhost:8082/signup/customer/verify?email=jungds95@naver.com&code=c8oNfeln0A
